### ISSUE TITLE
Add package-lock.json validation GA

### ISSUE THREAD

**Issue by IgorKrupenja** [IgorKrupenja/nextjs-starter#59]
```yaml
    # Validates if package-lock.json is up to date
    # If this check fails, run `npm install` and commit the changes
    validate-package-lock-json:
        uses: ./.github/workflows/run-check.yml
        with:
            command: npx --yes package-lock-utd@1.x.x
```
